// <auto-generated />
using System;
using Hackaton2025.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hackaton2025.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.PastProcedure", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PastProcedures");
                });

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.PastProcedureJury", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PastProcedureId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PastProcedureId");

                    b.ToTable("PastProcedureJuries");
                });

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.PastProcedureJuryMember", b =>
                {
                    b.Property<string>("PastProcedureJuryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeacherId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PastProcedureJuryId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("PastProcedureJuryMembers");
                });

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Distance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("LastJuryMemberDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("SecondLastJuryMemberDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniversityFactultyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UniversityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UniversityFactultyId");

                    b.HasIndex("UniversityId");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.University", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.UniversityFaculty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniversityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("UniversityFaculties");
                });

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.PastProcedureJury", b =>
                {
                    b.HasOne("Hackaton2025.Domain.Models.Entities.PastProcedure", null)
                        .WithMany("Juries")
                        .HasForeignKey("PastProcedureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.PastProcedureJuryMember", b =>
                {
                    b.HasOne("Hackaton2025.Domain.Models.Entities.PastProcedureJury", "PastProcedureJury")
                        .WithMany("JuryMembers")
                        .HasForeignKey("PastProcedureJuryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hackaton2025.Domain.Models.Entities.Teacher", "Teacher")
                        .WithMany("JuryMembers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PastProcedureJury");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.Teacher", b =>
                {
                    b.HasOne("Hackaton2025.Domain.Models.Entities.UniversityFaculty", "UniversityFaculty")
                        .WithMany()
                        .HasForeignKey("UniversityFactultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hackaton2025.Domain.Models.Entities.University", "University")
                        .WithMany("Teachers")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("University");

                    b.Navigation("UniversityFaculty");
                });

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.UniversityFaculty", b =>
                {
                    b.HasOne("Hackaton2025.Domain.Models.Entities.University", null)
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.PastProcedure", b =>
                {
                    b.Navigation("Juries");
                });

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.PastProcedureJury", b =>
                {
                    b.Navigation("JuryMembers");
                });

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.Teacher", b =>
                {
                    b.Navigation("JuryMembers");
                });

            modelBuilder.Entity("Hackaton2025.Domain.Models.Entities.University", b =>
                {
                    b.Navigation("Faculties");

                    b.Navigation("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
